//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alısveristakip.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        public int SatisID { get; set; }
        public int Urun { get; set; }
        public int Adet { get; set; }
        public decimal Fiyat { get; set; }
        public System.DateTime Tarih { get; set; }
        public int KullanıcıID { get; set; }
        public bool Statatus { get; set; }
    
        public virtual kullanici kullanici { get; set; }
        public virtual urun urun1 { get; set; }
        public virtual urun urun2 { get; set; }
    }
}
